#!/bin/bash

#################################################################
########### VKSearch script (c) snoopcatt, 2010-2013 ############
########### Licensed under GNU GPL v2. ##########################
#################################################################

######################################################
sys_version="0.6b"
sys_temp='/tmp' 
sys_method='audio.search'
vkapi_token='3a582f82cd975ace6015cd56e3e6eb3fff57961dccec60850a6272915f547132d616ae4ea0330a19725b9'  # для получения нового токена пройдите по ссылке: https://oauth.vk.com/authorize?client_id=3723065&scope=audio,offline&redirect_uri=http://oauth.vk.com/blank.html&display=wap&response_type=token
cfg_save_to="."
cfg_new_playlist='1'
cfg_write_tags='0'
cfg_search_count='300'
cfg_request_lyrics='0'
cfg_mplayer='mplayer -playlist'
cfg_wget="wget -qO - "
cfg_silent_wget='wget -qO - '
cfg_mode='play'
cfg_silent_mode='0'
cfg_single_get='0'
######################################################

Info() {
 [ "$cfg_silent_mode" -ne 1 ] && echo "[$(date +%k:%M:%S)] $1" > /dev/stderr
 [ "$2" == "die" ] && exit 1
}

ShowHelp() {
 echo  "VKSearch $sys_version: Поиск, прослушивание и закачка музыки с сайта VKontakte.ru!"
 echo "Для работы скрипта не требуется авторизация ВКонтакте. by snoopcatt, © 2010-2013. Лицензировано под GNU GPL v2."
 echo -e "* Использование: vksearch [опции] запрос"
 echo -e "\t--help: показать это сообщение и закрыть vksearch\n"
 echo -e "\t--user-playlist: использовать плейлист пользователя по ID"
 echo -e "\t--search: использовать поиск по всей коллекции ВК\n"
 echo -e "\t--play: проиграть найденный список треков"
 echo -e "\t--get: скачать найденный список треков"
 echo -e "\t--play-one: проиграть один из найденных треков"
 echo -e "\t--get-one: скачать один трек"
 echo -e "\t--make-playlist: создать плейлист\n"
 echo -e "\t--count=N: искать N треков"
 echo -e "\t--save-to=PATH: сохранять плейлист и треки в указанный PATH"
 echo -e "\t--write-tags: записывать id3 теги в скачанные треки"
 echo -e "\t--get-lyrics: скачать текст песни"
 echo -e "\t--silent: тихий режим"

 exit 0
}

GetParams() {
for var in $@ 
do
 case $var in
  --help) ShowHelp;;
  --user-playlist) sys_method='audio.get' ;;
  --search) sys_method='audio.search' ;;
  --play) cfg_mode=play ;;
  --get) cfg_mode=get ;;
  --play-one) cfg_mode=play && cfg_search_count=1 ;;
  --get-one) cfg_mode=get && cfg_search_count=1 ;;
  --get-lyrics) cfg_mode=get-lyrics && cfg_search_count=1 && cfg_request_lyrics=1;;
  --make-playlist) cfg_mode=make-playlist ;;
  --count=*) cfg_search_count=$(echo $var | cut -d '=' -f 2) ;;
  --save-to=*) cfg_save_to=$(echo $var | cut -d '=' -f 2) ;;
  --write-tags) cfg_write_tags=1 ;;
  --silent) cfg_silent_mode=1 && cfg_wget="$cfg_silent_wget";;
  --*) Info "Ошибка разбора аргументов: Неизвестный параметр $var" die ;;
  *) [ -z "$query" ] && query="${var}" || query="${query} ${var}"  ;;
 esac
done
[ -z "$query" ] && ShowHelp
}

GetIdByLink() { 
  query="$1"
  wget --no-check-certificate "https://api.vk.com/method/users.get.xml?uids=$query&fields=uid" -qO -  |sed -n 's|<uid>\(.*\)</uid>|\1|p'|sed 's/^[ \t]*//'
}

Request() { 
 Info "Добро пожаловать в VKSearch $sys_version!"
 Info "Загрузка списка треков..."
 case $sys_method in
  "audio.get")
    echo "$query" | grep -qE '[a-zA-Zа-яА-Я]' && query=$(GetIdByLink $query)
    wget --no-check-certificate "https://api.vk.com/method/audio.get.xml?oid=$query&fields=uid&access_token=$vkapi_token" -qO "${sys_temp}/vksearch.out" 
    found=$(cat ${sys_temp}/vksearch.out | grep '<url>'|wc -l) ;;
  "audio.search")
    wget --no-check-certificate "https://api.vk.com/method/audio.search.xml?q=$query&sort=2&auto_complete=1&lyrics=${cfg_request_lyrics}&count=${cfg_search_count}&access_token=$vkapi_token" -qO "${sys_temp}/vksearch.out" 
    found=$(cat ${sys_temp}/vksearch.out | sed -ne 's,<count>\([^<]*\)</count>,\1,p'|sed 's/^[ \t]*//') ;;
  "audio.getLyrics")
    query="$(cat ${sys_temp}/vksearch.out | sed -n 's|<lyrics_id>\(.*\)</lyrics_id>|\1|p'|sed 's/^[ \t]*//')"
    wget --no-check-certificate "https://api.vk.com/method/audio.getLyrics.xml?lyrics_id=${query}&access_token=$vkapi_token" -qO "${sys_temp}/vksearch.lyrics" 
    found=$(cat ${sys_temp}/vksearch.out | grep '<url>'|wc -l) 
 esac

 error_msg="$(cat ${sys_temp}/vksearch.out | sed -n 's|<error_msg>\(.*\)</error_msg>|\1|p'|sed 's/^[ \t]*//' )"
 error_code="$(cat ${sys_temp}/vksearch.out | sed -n 's|<error_code>\(.*\)</error_code>|\1|p'|sed 's/^[ \t]*//')"
 [ -n "$error_msg" ] && Info "Ошибка: $error_msg (Код $error_code)" die
 
 song_count=$(cat ${sys_temp}/vksearch.out | grep '<url>'|wc -l )
 [ $song_count -eq 0 ] && Info "По запросу ${query} не найдено ни одного трека..." die || Info "По запросу ${query} найдено ${found} композиций. Обработка первых ${song_count}."
}

Parse() { 
 OLD_IFS=$IFS
 IFS=$'\n'
 song_urls=( `cat ${sys_temp}/vksearch.out | sed -n 's|<url>\(.*\)</url>|\1|p'|sed 's/^[ \t]*//' ` )
 song_artists=( `cat ${sys_temp}/vksearch.out | sed -n 's|<artist>\(.*\)</artist>|\1|p'|sed 's/^[ \t]*//' ` )
 song_titles=( `cat ${sys_temp}/vksearch.out | sed -n 's|<title>\(.*\)</title>|\1|p'|sed 's/^  //' ` )
 song_durations=( `cat ${sys_temp}/vksearch.out |sed -n 's|<duration>\(.*\)</duration>|\1|p'|sed 's/^[ \t]*//' ` )
 song_counts=$(( ${#song_urls[@]} - 1 ))
 IFS=$OLD_IFS
}

MakePlaylist() {
 [ $cfg_new_playlist -eq 1 ] && rm $cfg_save_to/VKontakte_PlayList.pls 2>&-
 [ -f "$cfg_save_to/VKontakte_PlayList.pls" ] || echo "[playlist]" > "$cfg_save_to/VKontakte_PlayList.pls"
 current_number=0
 for i in `seq 0 $song_counts` ; do
   current_number=$(($i+1))
   echo -e "File${current_number}=${song_urls[$i]}\nTitle${current_number}=${song_artists[$i]} - ${song_titles[$i]}\nLength${current_number}=${song_durations[$i]}" >> "$cfg_save_to/VKontakte_PlayList.pls"
 done
 echo -e "NumberOfEntries=${current_number}\nVersion=2" >> "$cfg_save_to/VKontakte_PlayList.pls" ;
 [ -f "$cfg_save_to/VKontakte_PlayList.pls" ] && Info "Плейлист сохранен как $cfg_save_to/VKontakte_PlayList.pls" 
}

GetFiles() {
 cd "$cfg_save_to"
 for i in `seq 0 $song_counts` 
  do
   Info "Начинаю закачку: ${song_artists[$i]} - ${song_titles[$i]}"
   $cfg_wget "${song_urls[$i]}" > "${song_artists[$i]} - ${song_titles[$i]}.mp3" 
   Info "Файл ${song_artists[$i]} - ${song_titles[$i]} был загружен!"
   [ "$cfg_write_tags" -eq 1 ]  &&  id3 -2 -a "${song_artists[$i]}" -t "${song_titles[$i]}" "${song_artists[$i]} - ${song_titles[$i]}.mp3"
  done
 [ "$cfg_silent_mode" -eq 1 ] && echo "${song_artists[$i]} - ${song_titles[$i]}.mp3" 
}

GetLyrics() {
 cd "$cfg_save_to"
 cat ${sys_temp}/vksearch.lyrics|sed 's/<.*>//g;s/&quot;/"/g;/^[[:space:]]*$/d' > "${song_artists[0]} - ${song_titles[0]}.txt"
 Info "Текст песни ${song_artists[0]} - ${song_titles[0]} сохранён!"
 [ "$cfg_silent_mode" -eq 1 ] && echo "${song_artists[$i]} - ${song_titles[$i]}.txt" 
}

mkdir -p ${sys_temp}
GetParams $*
Request
Parse

case $cfg_mode in
 play)
    MakePlaylist
    ${cfg_mplayer} "$cfg_save_to/VKontakte_PlayList.pls" ;;
 get)
    GetFiles ;; 
 make-playlist)
    MakePlaylist ;;
 get-lyrics)
    sys_method="audio.getLyrics"
    Request
    GetLyrics ;;
esac
